### ISSUE TITLE
Using negative amounts for income transactions are confusing.

### ISSUE THREAD

**Issue by frouzbeh** [plaid/sandbox-custom-users#29]
In the sandbox custom user override data, income transactions (direct deposits, social security payments, interest) are marked with negative amounts for depository accounts:

```json
{
    "type": "depository",
    "subtype": "checking",
    "transactions": [
        {
            "amount": -2000,
            "description": "Plaid Direct Dep",
        },
        {
            "amount": -2500,
            "description": "Social Security Administration",
        }
    ]
}
```
This seems counterintuitive because:
- For depository accounts, positive amounts typically represent money coming IN
- Negative amounts typically represent money going OUT
- This pattern makes it difficult to correctly identify income vs expense transactions

Is this intended behavior? If so, could you explain the reasoning behind using negative amounts for incoming funds?
This would help developers implement correct transaction classification logic in their applications.

**Comment by phoenixy1** [comment]
I agree this isn't intuitive. It's historical and I believe (I'm not 100% positive, but this is what I gather) built on the very original use case of Plaid being used to get spending data from credit cards. In that scenario, spending made sense to represent as positive, and income made sense to represent as negative. That model was then applied to other account types and products. 

The Income product flips this (in Income endpoints, unlike other Plaid product endpoints, income is positive and spending is negative) but because Sandbox data is shared across multiple products, Income doesn't have its own unique representation for creating transactions in the Sandbox custom user object. Instead, a shared schema is used based on the model for the Transaction product.

I hope that made some degree of sense :-)

**Comment by frouzbeh** [comment]
Ah, I guess that makes sense. Thank you for the quick response. I believe I already requested Income product for my sandbox, so if I use Income, the values would be flipped?

**Comment by phoenixy1** [comment]
@frouzbeh when using the Income *endpoints*, the values will be flipped (e.g. a value entered as -500 in the transaction history will show up as positive 500 when returned by an Income endpoint.) However, the way the Sandbox is configured remains the same, using the negative values.
